LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
include $(LOCAL_PATH)/ENGINE_INCLUDES.mk
include $(LOCAL_PATH)/ENGINE_SRC_FILES.mk

LOCAL_CFLAGS := -DPLATFORM_ANDROID
LOCAL_CFLAGS += -DHAVE_EASTL
LOCAL_CFLAGS += -DMEMORY_ALLOCATOR
LOCAL_CFLAGS += -DTHREAD_COUNT=3
LOCAL_CFLAGS += -DGLES_VER=300

LOCAL_CPPFLAGS := -std=c++14
LOCAL_CPPFLAGS += -DPLATFORM_ANDROID
LOCAL_CPPFLAGS += -DHAVE_EASTL
LOCAL_CPPFLAGS += -DMEMORY_ALLOCATOR
LOCAL_CPPFLAGS += -DTHREAD_COUNT=3
LOCAL_CPPFLAGS += -DGLES_VER=300
LOCAL_CPPFLAGS += -fexceptions
LOCAL_CPPFLAGS += -frtti

LOCAL_LDLIBS := -llog -lGLESv3 -lEGL

LOCAL_MODULE := Engine
LOCAL_C_INCLUDES := $(ENGINE_INCLUDES)
LOCAL_SRC_FILES := $(ENGINE_SRC_FILES)
include $(BUILD_SHARED_LIBRARY)