GFX_RENDERER_SRC_FILES := \
../../Engine/Base/src/File.cpp \
../../Engine/Base/src/FileManager.cpp \
../../Engine/Base/src/Lock.cpp \
../../Engine/Base/src/nvwa/debug_new.cpp \
../../Engine/Base/src/nvwa/operator_new.cpp \
../../Engine/Base/src/Stream.cpp \
../../Engine/Base/src/TaskGraph.cpp \
../../Engine/Base/src/Utils.cpp \
../../Engine/Memory/src/Allocator.cpp \
../../Engine/Memory/src/MemoryHeap.cpp \
../../Engine/Memory/src/MemoryPool.cpp \
../../Engine/Memory/src/MemorySystem.cpp \
../../Engine/Renderer/Compiler/src/ShaderCompiler.cpp \
../../Engine/Renderer/Gfx/src/GfxCamera.cpp \
../../Engine/Renderer/Gfx/src/GfxProfiler.cpp \
../../Engine/Renderer/Gfx/src/GfxRenderer.cpp \
../../Engine/Renderer/Gfx/src/GfxRenderQueue.cpp \
../../Engine/Renderer/Gfx/src/GfxResource.cpp \
../../Engine/Renderer/Gfx/src/GfxResourceManager.cpp \
../../Engine/Renderer/Gfx/src/GfxVertexAttribute.cpp \
../../Engine/Renderer/GLES3/src/GLES30PipelineBase.cpp \
../../Engine/Renderer/GLES3/src/GLES30PipelineCompute.cpp \
../../Engine/Renderer/GLES3/src/GLES30PipelineGraphics.cpp \
../../Engine/Renderer/GLES3/src/GLES30Shader.cpp \
../../Engine/Renderer/GLES3/src/GLES31PipelineBase.cpp \
../../Engine/Renderer/GLES3/src/GLES31PipelineCompute.cpp \
../../Engine/Renderer/GLES3/src/GLES31PipelineGraphics.cpp \
../../Engine/Renderer/GLES3/src/GLES31Shader.cpp \
../../Engine/Renderer/GLES3/src/GLES3CommandBuffer.cpp \
../../Engine/Renderer/GLES3/src/GLES3CommandBufferManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3DrawIndirectBuffer.cpp \
../../Engine/Renderer/GLES3/src/GLES3Extension.cpp \
../../Engine/Renderer/GLES3/src/GLES3FrameBuffer.cpp \
../../Engine/Renderer/GLES3/src/GLES3FrameBufferManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3IndexBuffer.cpp \
../../Engine/Renderer/GLES3/src/GLES3InstanceBuffer.cpp \
../../Engine/Renderer/GLES3/src/GLES3Material.cpp \
../../Engine/Renderer/GLES3/src/GLES3MaterialManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3MaterialPass.cpp \
../../Engine/Renderer/GLES3/src/GLES3Mesh.cpp \
../../Engine/Renderer/GLES3/src/GLES3MeshManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3PipelineManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3Renderer.cpp \
../../Engine/Renderer/GLES3/src/GLES3RenderPass.cpp \
../../Engine/Renderer/GLES3/src/GLES3RenderPassManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3Sampler.cpp \
../../Engine/Renderer/GLES3/src/GLES3SamplerManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3ShaderManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3SwapChain.cpp \
../../Engine/Renderer/GLES3/src/GLES3Texture2D.cpp \
../../Engine/Renderer/GLES3/src/GLES3Texture2DArray.cpp \
../../Engine/Renderer/GLES3/src/GLES3TextureBase.cpp \
../../Engine/Renderer/GLES3/src/GLES3TextureCubeMap.cpp \
../../Engine/Renderer/GLES3/src/GLES3TextureManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformBase.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformBuffer.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformCamera.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformEngine.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformManager.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformMat4.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformVec1.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformVec2.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformVec3.cpp \
../../Engine/Renderer/GLES3/src/GLES3UniformVec4.cpp \
../../Engine/Renderer/GLES3/src/GLES3VertexArrayObject.cpp \
../../Engine/Renderer/GLES3/src/GLES3VertexBuffer.cpp \
../../Engine/ThirdParty/eastl/source/allocator_eastl.cpp \
../../Engine/ThirdParty/eastl/source/assert.cpp \
../../Engine/ThirdParty/eastl/source/fixed_pool.cpp \
../../Engine/ThirdParty/eastl/source/hashtable.cpp \
../../Engine/ThirdParty/eastl/source/intrusive_list.cpp \
../../Engine/ThirdParty/eastl/source/new.cpp \
../../Engine/ThirdParty/eastl/source/numeric_limits.cpp \
../../Engine/ThirdParty/eastl/source/red_black_tree.cpp \
../../Engine/ThirdParty/eastl/source/string.cpp \
../../Engine/ThirdParty/eastl/source/thread_support.cpp \
../../ThirdParty/event/event.c \
../../ThirdParty/gl3w/gl3w.c \
../../ThirdParty/glslc/file_includer.cc \
../../ThirdParty/lodepng/lodepng.cpp \
../../ThirdParty/rbtree/rbtree.cpp \
../../ThirdParty/spirv-cross/spirv_cfg.cpp \
../../ThirdParty/spirv-cross/spirv_cpp.cpp \
../../ThirdParty/spirv-cross/spirv_cross.cpp \
../../ThirdParty/spirv-cross/spirv_glsl.cpp \
../../ThirdParty/spirv-cross/spirv_hlsl.cpp \
../../ThirdParty/spirv-cross/spirv_msl.cpp \
../../ThirdParty/tinyxml/tinystr.cpp \
../../ThirdParty/tinyxml/tinyxml.cpp \
../../ThirdParty/tinyxml/tinyxmlerror.cpp \
../../ThirdParty/tinyxml/tinyxmlparser.cpp \
../../ThirdParty/zlib/adler32.c \
../../ThirdParty/zlib/compress.c \
../../ThirdParty/zlib/crc32.c \
../../ThirdParty/zlib/deflate.c \
../../ThirdParty/zlib/gzclose.c \
../../ThirdParty/zlib/gzlib.c \
../../ThirdParty/zlib/gzread.c \
../../ThirdParty/zlib/gzwrite.c \
../../ThirdParty/zlib/infback.c \
../../ThirdParty/zlib/inffast.c \
../../ThirdParty/zlib/inflate.c \
../../ThirdParty/zlib/inftrees.c \
../../ThirdParty/zlib/trees.c \
../../ThirdParty/zlib/uncompr.c \
../../ThirdParty/zlib/zutil.c \
../../ThirdParty/zzip/dir.c \
../../ThirdParty/zzip/err.c \
../../ThirdParty/zzip/fetch.c \
../../ThirdParty/zzip/file.c \
../../ThirdParty/zzip/info.c \
../../ThirdParty/zzip/plugin.c \
../../ThirdParty/zzip/stat.c \
../../ThirdParty/zzip/zip.c
